spring:
  application:
    name: microservice-api-gateway
server:
  port: 8050

zuul:
#  ignored-services: microservice-provider-user                        # 需要忽视的服务(配置后将不会被路由)
  routes:
    movie:                                                            # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /user/**                                                 # 想要映射到的路径
      service-id: microservice-provider-user     # Eureka中的serviceId


#zuul:
#  routes:
#    movie:
#      path: /user1/**                 # 想要映射到的路径
#      url: http://127.0.0.1:8071/     # 服务地址
